# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file
# within a transaction, strongly recommended for
# production environments
# transactional_ddl = false

# set to 'true' to use batch mode for SQLite migrations
# batch_mode = false

# set to 'true' to enable logging of migration statements
# log_sql = false

# set to 'true' to enable echoing of SQL commands
# echo_sql = false

# set to 'true' to run migrations in 'offline' mode.
# by default, migrations run in 'online' mode.
# offline mode ensures that the migration script
# can run without a database connection.
# offline_mode = false

# database url
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/chicken_shop_db

[post_write_hooks]
# post write hook for sqlite_check_foreign_keys
# type = sqlite_check_foreign_keys

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
qualname =

[formatter_generic]
format = %%(levelname)-8s %%(name)s %%(message)s
datefmt = %%Y-%%m-%%d %%H:%%M:%%S